def calculate_platform_fee(total_pool, percentage):
    """
    Calculate platform/service fee.
    """

    return int((total_pool * percentage) / 100)


def calculate_winner_payout(total_pool, service_fee):
    """
    Winner receives everything remaining after platform fee.
    """

    return total_pool - service_fee


def calculate_withdrawal_commission(amount, percentage):
    """
    Calculate referral commission generated by a withdrawal.
    """

    return int((amount * percentage) / 100)