# Generated by Django 6.0.2 on 2026-06-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_token', models.CharField(db_index=True, max_length=150)),
                ('amount', models.PositiveIntegerField()),
                ('method', models.CharField(choices=[('JAZZCASH', 'JazzCash'), ('EASYPAISA', 'EasyPaisa'), ('BINANCE', 'Binance')], max_length=20)),
                ('account_title', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofilebalance',
            name='coins',
            field=models.IntegerField(default=0),
        ),
    ]
