# Generated by Django 6.0.2 on 2026-06-19 23:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_withdrawalrequest_alter_userprofilebalance_coins'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilebalance',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp of row insertion.'),
        ),
        migrations.AddField(
            model_name='userprofilebalance',
            name='locked_coins',
            field=models.IntegerField(default=0, help_text='Escrowed coins held during active wagering matches.'),
        ),
        migrations.AddField(
            model_name='userprofilebalance',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp of last update verification.'),
        ),
        migrations.AlterField(
            model_name='userprofilebalance',
            name='coins',
            field=models.IntegerField(default=0, help_text='Available active balance spending pool.'),
        ),
        migrations.AlterField(
            model_name='userprofilebalance',
            name='device_token',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('bet_amount', models.IntegerField(default=0, help_text='Wager fee requirement per individual player profile.')),
                ('total_pool_escrow', models.IntegerField(default=0, help_text='Total 50/50 pooled contribution values.')),
                ('service_fee_cut', models.IntegerField(default=0, help_text='Calculated 15% system administration platform tax.')),
                ('winner_payout', models.IntegerField(default=0, help_text='Calculated 85% delivery distribution payload sum.')),
                ('game_status', models.CharField(choices=[('LOBBY', 'Lobby Waiting Frame'), ('ACTIVE', 'Active Wagering Match'), ('COMPLETED', 'Completed Ledger Payout'), ('CANCELLED', 'Rollback Cancelled Fail-Safe')], default='LOBBY', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('players', models.ManyToManyField(blank=True, related_name='active_wager_rooms', to='myapp.userprofilebalance')),
            ],
        ),
    ]
