# Generated by Django 6.0.2 on 2026-06-20 10:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_userprofilebalance_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdrawal_commission_percentage', models.PositiveIntegerField(default=5, help_text='Bonus cut percentage given to referrer upon an approved withdrawal.')),
                ('platform_tax_percentage', models.PositiveIntegerField(default=15, help_text='Wager pool platform tax percentage collected from match pools.')),
                ('winner_payout_percentage', models.PositiveIntegerField(default=85, help_text='Wager pool payout delivery payload percentage distributed to the winner.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global System Configuration',
                'verbose_name_plural': 'Global System Configuration',
            },
        ),
        migrations.AddField(
            model_name='userprofilebalance',
            name='referral_code',
            field=models.CharField(blank=True, db_index=True, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofilebalance',
            name='coins',
            field=models.IntegerField(default=0, help_text='Available active balance pool.'),
        ),
        migrations.AlterField(
            model_name='userprofilebalance',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userprofilebalance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ReferralSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_commission_earned', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by_link', to='myapp.userprofilebalance')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_initiated', to='myapp.userprofilebalance')),
            ],
        ),
        migrations.CreateModel(
            name='SystemTransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('log_type', models.CharField(choices=[('DEPOSIT', 'Manual Deposit Inflow'), ('WITHDRAWAL', 'Manual Withdrawal Outflow'), ('WAGER_ESCROW', 'Match Entry Lock'), ('WAGER_PAYOUT', 'Match Win Distribution'), ('REFERRAL_BONUS', 'Onboarding Sign-up Bonus'), ('REFERRAL_COMMISSION', 'Dynamic Withdrawal Bonus Reward')], max_length=25)),
                ('reference_id', models.CharField(blank=True, help_text='Tracks match IDs or request tracking IDs.', max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_traces', to='myapp.userprofilebalance')),
            ],
        ),
    ]
