# Generated by Django 6.0.2 on 2026-06-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_systemconfiguration_userprofilebalance_referral_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='service_fee_cut',
            field=models.IntegerField(default=0, help_text='System administration platform tax calculated dynamically from setup configurations.'),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='total_pool_escrow',
            field=models.IntegerField(default=0, help_text='Total pooled contribution values in escrow.'),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='winner_payout',
            field=models.IntegerField(default=0, help_text='Delivery distribution payload sum calculated dynamically from setup configurations.'),
        ),
    ]
