# Generated by Django 6.0.2 on 2026-06-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_gameroom_service_fee_cut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilebalance',
            name='nickname',
            field=models.CharField(blank=True, help_text="User's custom display name.", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofilebalance',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Verified mobile number.', max_length=20, null=True, unique=True),
        ),
    ]
