# Generated by Django 6.0.2 on 2026-09-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_userprofilebalance_nickname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systempaymentmethod',
            name='method_type',
            field=models.CharField(choices=[('JAZZCASH', 'JazzCash'), ('EASYPAISA', 'EasyPaisa'), ('BINANCE', 'Binance'), ('NAYAPAY', 'Nayapay'), ('SADAPAY', 'Sadapay')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='method',
            field=models.CharField(choices=[('JAZZCASH', 'JazzCash'), ('EASYPAISA', 'EasyPaisa'), ('BINANCE', 'Binance'), ('NAYAPAY', 'Nayapay'), ('SADAPAY', 'Sadapay')], max_length=20),
        ),
    ]
