# Generated by Django 6.1 on 2026-08-21 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_userprofilebalance_nickname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralsystem',
            name='referred_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by_link', to='myapp.userprofilebalance'),
        ),
        migrations.AlterUniqueTogether(
            name='referralsystem',
            unique_together={('referred_user',)},
        ),
        migrations.AlterModelTable(
            name='referralsystem',
            table='referral_system',
        ),
    ]
